### PR TITLE
Migrate to Unity 2017

### PR DESCRIPTION
**Pull request by AustinKellar**
Contributors: Austin, Ian, Alfredo

Goal:
- Fix the controller bugs by moving to Unity 2017

What changed:
- Literally everything

How to test:
- Load up this branch in unity version 2017.4.21f1
- Make sure everything works
- Make a build and make sure everything works

### CODE REVIEW

**Comment by AustinKellar** [comment]
What wasn't working?

**Comment by JamesCoulter** [comment]
I can't start the game from the player selection scene, and if I load into the main scene directly, I get null references in the player input script. I can't move any of the characters, and no blocks spawn above. Also, the ground texture is still messed up, but that's a separate issue.

**Comment by AustinKellar** [comment]
Okay, the null reference error is strange. Can you screen shot the errors?

**Comment by JamesCoulter** [comment]
screenshot 118

**Comment by AustinKellar** [comment]
It looks like your match manager didn't load correctly. Could you try relaunching?

**Comment by AustinKellar** [comment]
Hmm, mine just works when I go into the scene with 1 controller. Are you sure you launched in the right version of unity?

**Comment by JamesCoulter** [comment]
I'm in 2017.4.21f1

**Comment by IanGRap** [comment]
Maybe delete your branch locally and redownload it?

**Comment by AustinKellar** [comment]
Yeah, coulter you may have to delete the repo and clone it again fresh

**Comment by JamesCoulter** [comment]
Okay, deleted the local branch and brought it back locally, that seems to have fixed the problems. Not really sure why that happened

**Comment by AustinKellar** [comment]
You were probably working in match manager, then unity and git got confused when you switched branches. It happened to Ian on Friday

**Pull request merged**
